backend:
  name: github
  repo: GEBRUIKER/REPO          # vervang met je eigen gebruiker/naam
  branch: main                  # of gh-pages, afhankelijk van je setup
  base_url: https://api.staticcms.org  # proxy voor GitHub OAuth

media_folder: "images/uploads"  # waar geüploade afbeeldingen komen
public_folder: "/images/uploads"

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Titel", name: "title", widget: "string"}
      - {label: "Publicatiedatum", name: "date", widget: "datetime"}
      - {label: "Inhoud", name: "body", widget: "markdown"}
