backend:
  name: github
  repo: evilskunk-hub/cyborgdolfijn
  branch: main

media_folder: "images/uploads"  # waar geüploade afbeeldingen komen
public_folder: "/images/uploads"

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Titel", name: "title", widget: "string"}
      - {label: "Publicatiedatum", name: "date", widget: "datetime"}
      - {label: "Inhoud", name: "body", widget: "markdown"}
