backend:
  name: github
  repo: evilskunk-hub/cyborgdolfijn        # vervang door jouw GitHub-gebruiker en repository
  branch: main                # of gh-pages, afhankelijk van waar je site draait

media_folder: "images/uploads"   # map waar geüploade afbeeldingen in de repo komen
public_folder: "/images/uploads" # publiek pad waar de site de afbeeldingen vindt

collections:
  - name: "blog"              # interne naam
    label: "Blog"             # wat je in het CMS ziet
    folder: "content/blog"    # map in je repo voor de Markdown-bestanden
    create: true              # nieuwe posts kunnen aanmaken
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Titel", name: "title", widget: "string" }
      - { label: "Datum", name: "date", widget: "datetime" }
      - { label: "Inhoud", name: "body", widget: "markdown" }
